version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
  api1:
    build:
      context: ./api1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"
  api2:
    build:
      context: ./api2
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"
